# Generated by Django 4.2.2 on 2024-05-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='IssueType',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='issue',
            name='file_field',
            field=models.FileField(default='default_file.txt', upload_to='uploads/'),
        ),
    ]
