# Generated by Django 5.0.4 on 2024-05-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0002_alter_issue_issuename_alter_issue_assigned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='IssueType',
            field=models.CharField(default='', max_length=15),
        ),
    ]
