# Generated by Django 4.2.2 on 2024-05-09 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0003_remove_epic_guide_epic_asignee_epic_assigned_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epic',
            old_name='asignee',
            new_name='assignee',
        ),
        migrations.RenameField(
            model_name='epic',
            old_name='discription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='epic',
            name='projectId',
            field=models.ForeignKey(blank=True, default='null', null=True, on_delete=django.db.models.deletion.SET_NULL, to='djapp.project'),
        ),
    ]
