# Generated by Django 4.2.2 on 2024-05-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0003_remove_issue_issueid_issue_issue_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='assigned_epic',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='description',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='is_addedTosprint',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='projectId',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='sprint',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='status',
        ),
    ]
