# Generated by Django 5.0.4 on 2024-05-09 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0004_remove_issue_assigned_by_remove_issue_assigned_epic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='assigned_by',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='issue',
            name='assigned_epic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djapp.epic'),
        ),
        migrations.AddField(
            model_name='issue',
            name='assignee',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='issue',
            name='description',
            field=models.TextField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_addedTosprint',
            field=models.BooleanField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='projectId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djapp.project'),
        ),
        migrations.AddField(
            model_name='issue',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djapp.sprint'),
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(default='TODO', max_length=30),
        ),
    ]
