# Generated by Django 4.2.2 on 2024-05-08 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0004_remove_issue_assigned_by_remove_issue_assigned_epic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='projectId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djapp.project'),
        ),
    ]
