# Generated by Django 5.0.4 on 2024-05-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0005_issue_assigned_by_issue_assigned_epic_issue_assignee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='is_addedTosprint',
        ),
        migrations.AlterField(
            model_name='issue',
            name='assigned_by',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
